sudo: false
language: scala
script: "sbt clean coverage test"
after_script:
  - "sbt coveralls"
scala:
  - "2.11.7"
jdk:
  - oraclejdk7
  - openjdk7

before_install:
  - ./install-redis.sh
  - gem install redis
env:
  global:  
    - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"
    - REDIS_HOME=redis-3.2.0/src
# whitelist
branches:
  only:
    - master
