language: scala
script: sbt ++$TRAVIS_SCALA_VERSION "test-only * -- -exclude benchmark --"
scala:
  - "2.10.1"
  - "2.10.0"
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
services:
  - redis
env:
  - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"
